
version: "3.7"
services:

  db:
    container_name: gem-flow-db
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: gem-flow-app
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db-data:
