
version: "3.7"
services:

  db:
    container_name: gem-flow-db
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: gem-flow-server
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db

  ui:
    container_name: gem-flow-ui
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db-data:
