
version: "3.7"
services:

  database:
    container_name: gem-flow-database
    build: ./database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - gem-flow-db-data:/var/lib/postgresql/data

  # server:
  #   container_name: gem-flow-server
  #   build: ./server
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - database

  # ui:
  #   container_name: gem-flow-ui
  #   build: ./ui
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server

volumes:
  gem-flow-db-data:
